apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-config
  namespace: fiapgames
  labels:
    app: catalog-api
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  RabbitMq__Host: "rabbitmq.fiapgames.svc.cluster.local"
  RabbitMq__VirtualHost: "/"
