apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  namespace: fiapgames
  labels:
    app: catalog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      initContainers:
        - name: wait-for-sqlserver
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z -w 2 sqlserver.fiapgames.svc.cluster.local 1433; do
                echo "waiting for sqlserver..."
                sleep 2
              done
      containers:
        - name: catalog-api
          image: brendhom/fiapgames-catalog-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: catalog-api-config
            - secretRef:
                name: catalog-api-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api
  namespace: fiapgames
  labels:
    app: catalog-api
spec:
  selector:
    app: catalog-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
