<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>fiapgames-catalog</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FiapGames.Contracts" Version="1.1.0" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="NewRelic.Agent" Version="10.53.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FiapGames.Core\FiapGames.Core.csproj" />
    <ProjectReference Include="..\FiapGames.Data\FiapGames.Data.csproj" />
    <ProjectReference Include="..\FiapGames.Services\FiapGames.Services.csproj" />
  </ItemGroup>

</Project>
